<a href="https://colab.research.google.com/github/NagatoARS/Works_numpy-pandas/blob/main/%D0%94%D0%B7_%D0%BF%D0%BE_%D0%BD%D0%B0%D0%BC%D0%BF%D0%B8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1

In [ ]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
f'Введите число'
N=int(input())
print('Итог: {}'. format(np.arange(N-1, -1, -1)))

10
Итог: [9 8 7 6 5 4 3 2 1 0]


Задание 2

In [ ]:
import numpy as np
f'Введите число'
N=int(input())
matrix=np.diag(np.arange(N,0,-1))
sum=0
for line in matrix:
  for j in line:
    sum+=j
print('Сумма: {}'. format(sum))

10
Сумма: 55


Задание 3

In [ ]:
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
from numpy import linalg
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4

In [ ]:
import numpy as np
 
users_stats = np.array(
[
[2, 1, 0, 0, 0, 0],
[1, 1, 2, 1, 0, 0],
[2, 0, 1, 0, 0, 0],
[1, 1, 2, 1, 0, 1],
[0, 0, 1, 2, 0, 0],
[0, 0, 0, 0, 0, 5],
[1, 0, 0, 0, 0, 0],
[0, 1, 1, 0, 0, 0],
[0, 0, 0, 1, 1, 3],
[1, 0, 0, 2, 1, 4]
],
np.int32
)
 
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
 
cosine=np.dot(users_stats, next_user_stats)/(np.linalg.norm(users_stats, axis=1))/np.linalg.norm(next_user_stats)
idx=np.argmax(cosine)
print(users_stats[idx, :])

[0 1 1 0 0 0]
